version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    networks:
      - my_bridge_network

  backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - my_bridge_network

  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - my_bridge_network

      
volumes:
    mongodata:

networks:
    my_bridge_network:
